// an object to be imported  , it has type (answer or question) and text (the content of the message)
export const inputs = [
  {
    id: 0,
    type: "choice",
    title: "notRepairedDamage",
    question: "Est-ce que la voiture a des dommages non réparés ?",
    options: ["oui", "non"],
    answer: "",
  },
  {
    id: 1,
    type: "choice",
    title: "type",
    question: "Quel est le type du véhicule ?",
    options: ["suv", "limousine", "wagen", "cabriole", "bus", "coupe"],
    answer: "",
  },

  {
    id: 2,
    type: "text",
    title: "powerPS",
    question: "Quelle est la puissance de votre voiture ? (en chevaux)",
    answer: "",
  },
  {
    id: 3,
    type: "choice",
    title: "gearbox",
    question: "Quelle est la boîte de vitesses du véhicule ?",
    options: ["manuelle", "automatique"],
    answer: "",
  },
  {
    id: 4,
    type: "text",
    title: "brand",
    question: "Quelle est la marque du véhicule ?",
    answer: "",
  },
  {
    id: 5,
    type: "choice",
    title: "fuelType",
    question: "Quel est le type de carburant du véhicule ?",
    options: ["essence", "diesel", "gaz", "hybride", "electrique"],
    answer: "",
  },
  {
    id: 6,
    type: "text",
    title: "yearOfRegistration",
    question: "Quelle est l'année d'immatriculation du véhicule ?",
    answer: "",
  },
  {
    id: 7,
    type: "text",
    title: "kilometer",
    question: "Quel est le kilométrage de la voiture ?",
    answer: "",
  },
  {
    id: 8,
    type: "choice",
    title: "modifed",
    question: "Est-ce que la voiture a été modifiée ?",
    options: ["oui", "non"],
    answer: "",
  },
  {
    id: 9,
    type: "multi",
    title: "options",
    question: "Quelles sont les options de la voiture ?",
    options: [
      "airbag",
      "climatisation",
      "toitOuvrant",
      "siegesChauffants",
      "siegesElectriques",
      "vitresElectriques",
      "radio",
      "gps",
      "radarDeRecul",
      "jantesAlu",
      "attelage",
      "barresDeToit",
      "peintureMetalisee",
    ],
    answer: [],
  },
];
