/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Bot.gltf 
*/


import { useGLTF } from '@react-three/drei'


export default function BotModel(props) {


  const { nodes, materials } = useGLTF('/Bot.gltf')
  return (
    <group {...props}  dispose={null}  >
      <group position={[0, 1.507, 0]} scale={[1.463, 1, 1]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.Body} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[0, 1.507, 0]} scale={[1.463, 1, 1]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Screen} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0, 1.591, 0]} scale={[1.463, 1, 1]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.Body} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} scale={10.958} />
      <group position={[1.584, 1.141, 0.001]} rotation={[0, 0, -Math.PI / 2]} scale={0.906}>
        <mesh geometry={nodes.Circle005.geometry} material={materials.Body} />
        <mesh geometry={nodes.Circle005_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle005_2.geometry} material={materials.Wheel} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bot.gltf')

